# pull the official base image
FROM node:16-alpine
# set working direction
WORKDIR /app

# install application dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install
COPY . .

# give node user permissions
RUN chown -R node /app/node_modules
USER node
EXPOSE 3000

# start app
CMD ["npm", "run", "start"]

