version: "3"
services:
  postgres:
    image: mdillon/postgis:11 #this may affect drivers for rstudio!
    ports:
      - "35432:5432"
    env_file: ./envs/db.env
    volumes:
      - ./pg/data:/var/lib/postgresql/data

  rstudio:
    build:
      context: ./rstudio/
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8787:8787"
    env_file: ./envs/rstudio.env
    volumes:
      - ./rstudio/data:/home/rstudio/pp-pipeline/data
      - ./rstudio/scripts:/home/rstudio/pp-pipeline/scripts
