version: "3"
services:
  nginx:
    restart: unless-stopped
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - client
  api:
    build:
      context: ./server/
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file: ./envs/api-prod.env
    volumes:
      - ./server/:/app/
      - /app/node_modules

  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    env_file: ./envs/web.env
    volumes:
      - ./client/:/app/
      - /app/node_modules
