version: "3"
services:
  nginx:
    restart: always
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "3050:80"
    depends_on:
      - api
      - client
  api:
    build:
      context: ./server/
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file: ./envs/api-prod.env
    volumes:
      - ./server/:/app/
      - /app/node_modules

  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    env_file: ./envs/web.env
    volumes:
      - ./client/:/app/
      - /app/node_modules

  postgres:
    image: mdillon/postgis:11
    ports:
      - "35432:5432"
    env_file: ./envs/db.env

  rstudio:
    build:
      context: ./rstudio/
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8787:8787"
    env_file: ./envs/rstudio.env
    volumes:
      - ./rstudio/data:/home/rstudio/pp-pipeline/data
      - ./rstudio/scripts:/home/rstudio/pp-pipeline/scripts
