FROM rocker/geospatial:latest

RUN mkdir -p /home/rstudio/pp-pipeline/scripts \
    mkdir -p /home/rstudio/pp-pipeline/data/shps \
    mkdir -p /home/rstudio/pp-pipeline/data/csvs

##install ODBC drivers
RUN apt-get update \
 && apt-get install --yes --no-install-recommends \
    unixodbc unixodbc-dev odbc-postgresql libssl-dev \
    tzdata
###


RUN install2.r --error \
    devtools \
    dotenv \
    #boxr \
    odbc \
    #RPostgres \
    rpostgis \
    pacman
    
RUN R -e "install.packages('aws.s3', repos = c('cloudyr' = 'http://cloudyr.github.io/drat'))"
